apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: node-app-backend-service
spec:
  healthChecks:
  - healthCheckRef:
      name: node-app-backend-healthcheck
  protocol: HTTP
  location: global
