apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: {{ required "name is required!" .Values.cluster2.name }}
spec:
  location: {{ required "location is required!" .Values.cluster2.zone }}
  initialNodeCount: 2
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  ipAllocationPolicy:
    servicesIpv4CidrBlock: ""
  nodeConfig:
    oauthScopes:
    - "https://www.googleapis.com/auth/cloud-platform"
  workloadIdentityConfig:
    identityNamespace: '{{ required "identityNamespace is required!" .Values.projectId }}.svc.id.goog'
  masterAuth:
    username: '{{ required "username is required!" .Values.cluster2.masterAuthUser }}'
    password:
      valueFrom:
        secretKeyRef:
          name: cluster-2-secret-pwd
          key: password
    clientCertificateConfig:
      issueClientCertificate: false