apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: {{ required "name is required!" .Values.cluster1.name }}
spec:
  location: {{ required "location is required!" .Values.cluster1.zone }}
  initialNodeCount: 1
  loggingService: none
  nodeConfig:
    oauthScopes:
    - "https://www.googleapis.com/auth/cloud-platform"
  workloadIdentityConfig:
    identityNamespace: '{{ required "identityNamespace is required!" .Values.projectId }}.svc.id.goog'
  masterAuth:
    username: '{{ required "username is required!" .Values.cluster1.masterAuthUser }}'
    password:
      valueFrom:
        secretKeyRef:
          name: cluster-1-secret-pwd
          key: password
    clientCertificateConfig:
      issueClientCertificate: false