apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: {{ required "name is required!" .Values.cluster2.name }}
spec:
  ipAllocationPolicy:
    useIpAliases: true
  location: {{ required "location is required!" .Values.cluster2.zone }}
  initialNodeCount: 1
  removeDefaultNodePool: false
  loggingService: none
  nodeConfig:
    oauthScopes:
    - "https://www.googleapis.com/auth/cloud-platform"
  masterAuth:
    username: "user"
    password:
      valueFrom:
        secretKeyRef:
          name: cluster-2-secret-pwd
          key: password
    clientCertificateConfig:
      issueClientCertificate: false