apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: clf-anthos-cicd-test # {"$ref":"#/definitions/io.k8s.cli.setters.project-id"}
spec:
  # The Google Service Account used to authenticate Google Cloud APIs in this Namespace
  googleServiceAccount: "clf-anthos-cicd-test-cnrm@clf-gke-acm-dev.iam.gserviceaccount.com" # { "$kpt-set": "sa-email" }
